- name: Install Mesos-dns
  yum:
        name: /home/vagrant/sync/mesos-dns-0.4.0-0.el7.centos.x86_64.rpm
        state: present
- name: Configure Mesos-dns
  template:
        src: config.json.j2
        dest: /etc/mesos-dns/config.json
  notify: Restart Mesos-dns
- name: Enable Mesos-dns
  service:
        name: mesos-dns
        state: started
        enabled: yes
